## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/*"
  to = "https://sprout-cube-dsxe.squarespace.com/"
  status = 301

  [[redirects]]
  from = "https://devenir.netlify.app/"
  to = "https://sprout-cube-dsxe.squarespace.com/"
  status = 301

  [[redirects]]
  from = "/test"
  to = "https://sprout-cube-dsxe.squarespace.com/"
  status = 301